# This script appends the date suffix YYYYMMDD (Asia/Phnom_Penh) to the semver already written to version.json.

#!/usr/bin/env bash
set -e


ENV=${1:-production}
README="README.md"
VJSON=version.json


if [ ! -f "$VJSON" ]; then
echo "version.json not found"
exit 1
fi


# read semver for environment
SEMVER="$(node -e "console.log(require('../version.json')['${ENV}'] || '')")"


# If semver already contains prefix (LOCAL-/STAGING-) keep it
# Remove prefix and then re-add with date
PREFIX=""
if [[ "$SEMVER" == LOCAL-* ]]; then
PREFIX="LOCAL-"
NUMVER="${SEMVER#LOCAL-}"
elif [[ "$SEMVER" == STAGING-* ]]; then
PREFIX="STAGING-"
NUMVER="${SEMVER#STAGING-}"
else
NUMVER="$SEMVER"
fi


# Get date in Phnom Penh
DATE=$(TZ='Asia/Phnom_Penh' date +%Y%m%d)


if [ -z "$NUMVER" ]; then
echo "No version found in version.json for env $ENV"
exit 1
fi


NEW_VERSION="${PREFIX}${NUMVER}.${DATE}"


echo "Setting $ENV version to $NEW_VERSION"


# Update version.json with full string
node -e "let v=require('../version.json'); v['${ENV}']='${NEW_VERSION}'; require('fs').writeFileSync('version.json', JSON.stringify(v,null,2));"


# Replace HTML comment placeholder
perl -0777 -pe "s/<!-- VERSION:[^>]*-->/<!-- VERSION: ${NEW_VERSION} -->/s" -i "$README"


# Replace visible line like: Current version: x.y.z.DATE (first occurrence)
perl -0777 -pe "s/(Current version:\s*)[A-Za-z0-9\.-]+/\$1${NEW_VERSION}/s" -i "$README"


# Update CHANGELOG header if missing
if ! grep -q "# Changelog" CHANGELOG.md 2>/dev/null; then
echo "# Changelog\n" > CHANGELOG.md
fi


# Append a notice in CHANGELOG that new version was prepared (details will be generated by generate_changelog.js)
echo "\n## ${NEW_VERSION} - prepared on ${DATE}\n" >> CHANGELOG.md